### PR TITLE
fix: make d1 spaces.metadata nullable and change to kysely

### LINKED ISSUE #280: Access API - Auth Flow and Space registration Error
```
��dnameuHandlerExecutionErrorecause�dnamegD1ErrorestackyD1Error: Error: ERROR 9015: SQL engine error: failed to read next row: NOT NULL constraint failed: spaces.metadata (undefined)
    at Ps.create (d1-beta-facade.entry.js:10922:23)
    at async d1-beta-facade.entry.js:9135:24
    at async Ox (d1-beta-facade.entry.js:8274:12)
    at async Ix (d1-beta-facade.entry.js:8262:12)
    at async Bx (d1-beta-facade.entry.js:8256:42)
    at async km (d1-beta-facade.entry.js:9182:11)
    at async No.fetch (d1-beta-facade.entry.js:3685:17)
    at async Object.fetch (d1-beta-facade.entry.js:11332:13)gmessagexuError: ERROR 9015: SQL engine error: failed to read next row: NOT NULL constraint failed: spaces.metadata (undefined)eerror�estacky�HandlerExecutionError: service handler {can: "voucher/redeem"} error: Error: ERROR 9015: SQL engine error: failed to read next row: NOT NULL constraint failed: spaces.metadata (undefined)
    at Ox (d1-beta-facade.entry.js:8276:13)
    at async Ix (d1-beta-facade.entry.js:8262:12)
    at async Bx (d1-beta-facade.entry.js:8256:42)
    at async km (d1-beta-facade.entry.js:9182:11)
    at async No.fetch (d1-beta-facade.entry.js:3685:17)
    at async Object.fetch (d1-beta-facade.entry.js:11332:13)gmessagex�service handler {can: "voucher/redeem"} error: Error: ERROR 9015: SQL engine error: failed to read next row: NOT NULL constraint failed: spaces.metadata (undefined)jcapability�ccannvoucher/redeemdwithx8did:key:z6MkwTYX2JHHd8bmaEuDdS1LJjrpFspirjDcQ4DvAiDP49Gm
```

### PR DESCRIPTION
**Pull request by hugomrdias**
- spaces.metadata is now nullable
- d1 tables are now typed
- moved from `workers-qb` to [`kysely`](https://github.com/koskimas/kysely) with [d1 dialect](https://github.com/aidenwallis/kysely-d1) 

closes #280

### CODE REVIEW

File: packages/access-api/src/models/spaces.js [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+          /** @type {unknown} */ (invocation.facts[0])
+        )
+      const result = await this.d1
+        .withPlugin(spacePlugin)
+        .insertInto('spaces')
+        .values({
+          agent: invocation.issuer.did(),
+          did: capability.nb.space,
+          email: capability.nb.identity.replace('mailto:', ''),
+          invocation: await delegationToString(invocation),
```
Comment (alanshaw) [inline packages/access-api/src/models/spaces.js:43]: Are all these sync now?

File: packages/access-api/src/models/spaces.js [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+          metadata,
+          delegation: !delegation
+            ? undefined
+            : await delegationToString(delegation),
+        })
+        .returning('spaces.did')
+        .execute()
+      return { data: result }
+    } catch (error) {
+      return {
```
Comment (alanshaw) [inline packages/access-api/src/models/spaces.js:54]: Why return error and not throw?

**Review by alanshaw — APPROVED** [review]

File: packages/access-api/src/models/spaces.js (hunk 2 above)
Comment (hugomrdias) [reply packages/access-api/src/models/spaces.js:54]: cause i need to use the error on the provider side and i dont want to try catch the full provider logic. im working on normalising this all thing in the w3space/account refactor
